In [ ]:
pip install numpy

In [6]:
import numpy as np

#create a array
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.shape)

arr.reshape(1,4)
print(arr)

arr.reshape(4,1)
print(arr)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
[1 2 3 4]
[1 2 3 4]


In [ ]:
arr2 = np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.shape)


[[1 2 3 4 5]]
(1, 5)


In [10]:
#arrange is a fun use to create a array with define range

np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
#attribute of array

arr = np.array([[1,2,3,4],[5,6,7,8]])

print('Array:\n', arr)
print('Shape:', arr.shape)
print('Number of dimensions:',arr.ndim)
print('Size (no of elements):', arr.size)
print('Datatype:',arr.dtype)

Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Number of dimensions: 2
Size (no of elements): 8
Datatype: int32


In [ ]:
## numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#addition
print("Addition of arr1 & arr2: ",arr1+arr2)

#substraction
print("Substraction of arr1 & arr2: ", arr1-arr2)

#multiplication
print("Multiplication:", arr1*arr2)

#division
print("Division:", arr1/arr2)

#floor division 
print("floor Division:", arr1//arr2)

#modolu
print("modolus :", arr1%arr2)



Addition of arr1 & arr2:  [11 22 33 44 55]
Substraction of arr1 & arr2:  [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]
floor Division: [0 0 0 0 0]
modolus : [1 2 3 4 5]


In [31]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [35]:
#modify array

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [37]:
arr[1:]= 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [41]:
##statistical concept
#to have amean of 0 and std of 1

data = np.array([1, 2, 3, 4, 5])


mean = np.mean(data)
std_dev = np.std(data)

#normalise the data
normalised_data = (data -mean)/std_dev
print(normalised_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [42]:
data = np.array([1,2,3,4,5,6,7,8])

median = np.median(data)
mean = np.mean(data)

std_dev = np.std(data)

Variance = np.var(data)

print(median)
print(mean)
print(std_dev)

4.5
4.5
2.29128784747792


In [46]:
data=np.array([1,2,3,4,5,6,7,8,9,10])


print(data[data>5])

[ 6  7  8  9 10]
